# Generated by Django 6.1 on 2026-08-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Planned', 'Planned'), ('Decommissioned', 'Decommissioned')], max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
