# Generated by Django 6.1 on 2026-08-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='topology.site')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
