# Generated by Django 6.1 on 2026-08-13 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('speed', models.PositiveIntegerField(help_text='Throughput in Mbps; must be a positive integer.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Maintenance', 'Maintenance')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='topology.device')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'name'), name='unique_interface_name_per_device')],
            },
        ),
    ]
