# Generated by Django 6.1 on 2026-08-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], max_length=20)),
                ('end_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='topology.interface')),
                ('start_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='topology.interface')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
